version: "3"

services:
  postgres-server:
    image: postgres:14.0
    container_name: postgres-server
    ports:
      - 5432:5432
    env_file:
      - ./.env.prod
    healthcheck:
      test: ["CMD","pg_isready","-q","-U","myuser","-d","mydatabase"]
      interval: 10s
      timeout: 5s
      retries: 5 

  data-generator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: data_generator
    depends_on:
      postgres-server:
        condition: service_healthy
    command: ["postgres-server"]

networks:
  default:
    name: mlops-network
